### ISSUE TITLE
Unexpected behavior on new session connection

### ISSUE THREAD

**Issue by LukasJue** [drawr-team/drawrlib#1]
#https://github.com/drawr-team/core-lib/blob/master/src/lib/ServerConnection.js#L64

should only expect `example.com:8080`

ideally host: `example.com`, port: `8080`

Library has to construct websocket url from that by prepending `ws://` and appending `/<sessionId>/ws`

**Comment by pedroscaff** [comment]
will be fixed after merge of `new-http-server` branch.
